In [1]:
!pip install scikit-learn

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("/Users/myyntiimac/Desktop/ML Datar/Data.csv")
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [3]:
df.head()

State   Age   Salary Purchased
0     Mumbai  44.0  72000.0        No
1  Bangalore  27.0  48000.0       Yes
2  Hyderabad  30.0  54000.0        No
3  Bangalore  38.0  61000.0        No
4  Hyderabad  40.0      NaN       Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   State      10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [5]:
df.isnull()

State    Age  Salary  Purchased
0  False  False   False      False
1  False  False   False      False
2  False  False   False      False
3  False  False   False      False
4  False  False    True      False
5  False  False   False      False
6  False   True   False      False
7  False  False   False      False
8  False  False   False      False
9  False  False   False      False

In [10]:
X = df.iloc[:, :-1].values
X


array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, nan],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', nan, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [11]:
y= df.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [12]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='most_frequent')
imputer = imputer.fit(X[:,1:3]) 
X[:, 1:3] = imputer.transform(X[:,1:3])
X[:, 1:3]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, 48000.0],
       [35.0, 58000.0],
       [27.0, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder

labelencoder_X = LabelEncoder()

labelencoder_X.fit_transform(X[:,0]) 

X[:,0]=labelencoder_X.fit_transform(X[:,0]) #parameter of x
X[:,0]

array([2, 0, 1, 0, 1, 2, 0, 2, 1, 2], dtype=object)

In [14]:
#lebelencoding target variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)#parameter of y
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [15]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.3,random_state = 0 ) 

In [16]:
X_train

array([[2, 37.0, 67000.0],
       [0, 27.0, 48000.0],
       [0, 27.0, 52000.0],
       [2, 48.0, 79000.0],
       [0, 38.0, 61000.0],
       [2, 44.0, 72000.0],
       [2, 35.0, 58000.0]], dtype=object)

In [17]:
X_test

array([[1, 30.0, 54000.0],
       [1, 50.0, 83000.0],
       [1, 40.0, 48000.0]], dtype=object)

In [18]:
y_train

array([1, 1, 0, 1, 0, 0, 1])

In [19]:
y_test

array([0, 0, 1])

In [20]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.3) 

In [21]:
X_train

array([[2, 37.0, 67000.0],
       [0, 38.0, 61000.0],
       [0, 27.0, 48000.0],
       [2, 35.0, 58000.0],
       [0, 27.0, 52000.0],
       [1, 30.0, 54000.0],
       [1, 40.0, 48000.0]], dtype=object)

In [22]:
X_test

array([[1, 50.0, 83000.0],
       [2, 48.0, 79000.0],
       [2, 44.0, 72000.0]], dtype=object)

In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.25,random_state=2) 

In [24]:
X_train

array([[2, 44.0, 72000.0],
       [2, 48.0, 79000.0],
       [1, 30.0, 54000.0],
       [0, 38.0, 61000.0],
       [0, 27.0, 52000.0],
       [2, 37.0, 67000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [25]:
from sklearn.preprocessing import Normalizer

sc_X = Normalizer() 

X_train = sc_X.fit_transform(X_train)

X_test = sc_X.transform(X_test)

In [26]:
X_train

array([[2.77777726e-05, 6.11110997e-04, 9.99999813e-01],
       [2.53164510e-05, 6.07594824e-04, 9.99999815e-01],
       [1.85185157e-05, 5.55555470e-04, 9.99999846e-01],
       [0.00000000e+00, 6.22950699e-04, 9.99999806e-01],
       [0.00000000e+00, 5.19230699e-04, 9.99999865e-01],
       [2.98507417e-05, 5.52238722e-04, 9.99999847e-01],
       [1.20481906e-05, 6.02409529e-04, 9.99999818e-01]])

In [28]:
X_test 

array([[2.08333261e-05, 8.33333044e-04, 9.99999653e-01],
       [0.00000000e+00, 5.62499911e-04, 9.99999842e-01],
       [3.44827523e-05, 6.03448166e-04, 9.99999817e-01]])